<!doctype html>

<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet/less" href="source/less/style.less">
    <script async type="text/javascript" src="source/js/less.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body class="character-creation">
    <div class="content-wrapper">
        <div class="form-container">
            <form action="" method="get">
                <fieldset>
                    <legend>Character Creation</legend>
                    <div class="form-element-group">
                        <label for="name">Name</label>
                        <input type="text" autofocus="autofocus" required="required">
                    </div>
                    <div class="form-element-group">
                        <label for="class">Class</label>
                        <select id="charClass" required="required">
                            <option selected="selected">- class -</option>
                            <option>Mage</option>
                            <option>Priest</option>
                            <option>Ranger</option>
                            <option>Rogue</option>
                            <option>Warrior</option>
                        </select>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Character attributes</legend>
                    <div class="form-element-group">
                        <label>Strength</label>
                        <input class="attribute-number" data-str="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                    <div class="form-element-group">
                        <label>Dexterity</label>
                        <input class="attribute-number" data-dex="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                    <div class="form-element-group">
                        <label>Constitution</label>
                        <input class="attribute-number" data-con="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                    <div class="form-element-group">
                        <label>Intelligence</label>
                        <input class="attribute-number" data-int="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                    <div class="form-element-group">
                        <label>Wisdom</label>
                        <input class="attribute-number" data-wis="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                    <div class="form-element-group">
                        <label>Charisma</label>
                        <input class="attribute-number" data-cha="" type="text" required="required" readonly="readonly">
                        <button>Reroll</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</body>

<script>

classes = {

    mage: {
        int: 1,
        wis: 1,
        cha: 1,
        con: 0,
        str: 0,
        dex: -1,
    },
}

attributes = {

    init: function() {
        attributes.attachHandlers();
    },

    attachHandlers: function() {
        $('#charClass').change(attributes.calculateAttributeValues);
    },

    calculateAttributeValues: function() {
        var classVal = ($('#charClass').val()).toLowerCase();

        $('.attribute-number').each(function(index, element) {
            $(element).val(attributes.calculateAttributeValue(classVal));
        });
    },

    calculateAttributeValue: function(classVal) {
        for (var charClass in classes) {
            if (charClass == classVal) {
                for (var modifier in charClass) {
                    console.log(Math.floor(Math.random() * 10) + 11 + modifier);
                }
            }
        }
    },
};

attributes.init();

</script>
</html>
