<!doctype html>

<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet/less" href="source/less/style.less">
    <script async type="text/javascript" src="source/js/less.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body class="character-creation">
    <div class="content-wrapper">
        <div class="form-container">
            <form action="" method="get">
                <fieldset>
                    <legend>Character Creation</legend>
                    <div class="form-element-group">
                        <label for="name">Name</label>
                        <input type="text" autofocus="autofocus" required="required">
                    </div>
                    <div class="form-element-group">
                        <label for="class">Class</label>
                        <select id="charClass" required="required">
                            <option selected="selected">- class -</option>
                            <option>Mage</option>
                            <option>Priest</option>
                            <option>Ranger</option>
                            <option>Rogue</option>
                            <option>Warrior</option>
                        </select>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Character attributes</legend>
                    <div class="form-element-group">
                        <label>Strength</label>
                        <input class="attribute-number" data-class="str" type="number" required="required" readonly="readonly">
                    </div>
                    <div class="form-element-group">
                        <label>Dexterity</label>
                        <input class="attribute-number" data-class="dex" type="number" required="required" readonly="readonly">
                    </div>
                    <div class="form-element-group">
                        <label>Constitution</label>
                        <input class="attribute-number" data-class="con" type="number" required="required" readonly="readonly">
                    </div>
                    <div class="form-element-group">
                        <label>Intelligence</label>
                        <input class="attribute-number" data-class="int" type="number" required="required" readonly="readonly">
                    </div>
                    <div class="form-element-group">
                        <label>Wisdom</label>
                        <input class="attribute-number" data-class="wis" type="number" required="required" readonly="readonly">
                    </div>
                    <div class="form-element-group">
                        <label>Charisma</label>
                        <input class="attribute-number" data-class="cha" type="number" required="required" readonly="readonly">
                    </div>
                    <button id="reroll-stats">Reroll stats</button>
                </fieldset>
            </form>
        </div>
    </div>
</body>

<script>

classes = {

    mage: {
        int: 1,
        wis: 1,
        cha: 1,
        con: 0,
        str: 0,
        dex: -1,
    },
}

attributes = {

    init: function() {
        attributes.attachHandlers();
    },

    attachHandlers: function() {
        $('#charClass').change(attributes.calculateAttributeValues);
        $('#reroll-stats').click(attributes.rerollStats);
    },

    calculateAttributeValues: function() {
        var className = ($('#charClass').val()).toLowerCase();
        var attributeModifiers = attributes.getAttributeModifiers(className);

        for (var attribute in attributeModifiers) {
            var modifier = attributeModifiers[attribute];
            var val = Math.ceil(Math.random() * 10) + 10 + modifier;

            $('.attribute-number').each(function(index, input) {
                if ($(input).data('class') == attribute) {
                    $(input).val(val);
                }
            });
        }
    },

    getAttributeModifiers: function(className) {
        for (charClass in classes) {
            if (charClass == className) {
                return classes[className];
            }
        }
    },

    rerollStats: function(event) {
        event.preventDefault();
        attributes.calculateAttributeValues();
    }
};

attributes.init();

</script>
</html>
