<!doctype html>

<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet/less" href="source/less/style.less">
    <link rel="stylesheet/less" href="source/less/map.less">
    <script async type="text/javascript" src="source/js/less.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body class="map">
    <main>
        <table>
            <tbody>
                <!-- content set via js -->
            </tbody>
        </table>
        <input id="console-input" type="text">
    </main>
</body>
</html>

<script>
    var tiles = {
        '0,0' : ['orc', 'kobold', 'kobold'],
        '0,1' : ['orc', 'kobold', 'kobold'],
        '0,2' : ['orc', 'kobold', 'kobold'],
        '0,3' : ['orc', 'kobold', 'kobold'],
        '0,4' : ['orc', 'kobold', 'kobold'],
        '0,5' : ['orc', 'kobold', 'kobold'],
        '0,6' : ['orc', 'kobold', 'kobold'],
        '0,7' : ['orc', 'kobold', 'kobold'],
        '0,8' : ['orc', 'kobold', 'kobold'],
        '0,9' : ['orc', 'kobold', 'kobold'],
        '1,0' : ['orc', 'kobold', 'kobold'],
        '1,1' : ['orc', 'kobold', 'kobold'],
        '1,2' : ['orc', 'kobold', 'kobold'],
        '1,3' : ['orc', 'kobold', 'kobold'],
        '1,4' : ['orc', 'kobold', 'kobold'],
        '1,5' : ['orc', 'kobold', 'kobold'],
        '1,6' : ['orc', 'kobold', 'kobold'],
        '1,7' : ['orc', 'kobold', 'kobold'],
        '1,8' : ['orc', 'kobold', 'kobold'],
        '1,9' : ['orc', 'kobold', 'kobold'],
        '2,0' : ['orc', 'kobold', 'kobold'],
        '2,1' : ['orc', 'kobold', 'kobold'],
        '2,2' : ['orc', 'kobold', 'kobold'],
        '2,3' : ['orc', 'kobold', 'kobold'],
        '2,4' : ['orc', 'kobold', 'kobold'],
        '2,5' : ['orc', 'kobold', 'kobold'],
        '2,6' : ['orc', 'kobold', 'kobold'],
        '2,7' : ['orc', 'kobold', 'kobold'],
        '2,8' : ['orc', 'kobold', 'kobold'],
        '2,9' : ['orc', 'kobold', 'kobold'],
        '3,0' : ['orc', 'kobold', 'kobold'],
        '3,1' : ['orc', 'kobold', 'kobold'],
        '3,2' : ['orc', 'kobold', 'kobold'],
        '3,3' : ['orc', 'kobold', 'kobold'],
        '3,4' : ['orc', 'kobold', 'kobold'],
        '3,5' : ['orc', 'kobold', 'kobold'],
        '3,6' : ['orc', 'kobold', 'kobold'],
        '3,7' : ['orc', 'kobold', 'kobold'],
        '3,8' : ['orc', 'kobold', 'kobold'],
        '3,9' : ['orc', 'kobold', 'kobold'],
        '4,0' : ['orc', 'kobold', 'kobold'],
        '4,1' : ['orc', 'kobold', 'kobold'],
        '4,2' : ['orc', 'kobold', 'kobold'],
        '4,3' : ['orc', 'kobold', 'kobold'],
        '4,4' : ['orc', 'kobold', 'kobold'],
        '4,5' : ['orc', 'kobold', 'kobold'],
        '4,6' : ['orc', 'kobold', 'kobold'],
        '4,7' : ['orc', 'kobold', 'kobold'],
        '4,8' : ['orc', 'kobold', 'kobold'],
        '4,9' : ['orc', 'kobold', 'kobold'],
        '5,0' : ['orc', 'kobold', 'kobold'],
        '5,1' : ['orc', 'kobold', 'kobold'],
        '5,2' : ['orc', 'kobold', 'kobold'],
        '5,3' : ['orc', 'kobold', 'kobold'],
        '5,4' : ['orc', 'kobold', 'kobold'],
        '5,5' : ['orc', 'kobold', 'kobold'],
        '5,6' : ['orc', 'kobold', 'kobold'],
        '5,7' : ['orc', 'kobold', 'kobold'],
        '5,8' : ['orc', 'kobold', 'kobold'],
        '5,9' : ['orc', 'kobold', 'kobold'],
        '6,0' : ['orc', 'kobold', 'kobold'],
        '6,1' : ['orc', 'kobold', 'kobold'],
        '6,2' : ['orc', 'kobold', 'kobold'],
        '6,3' : ['orc', 'kobold', 'kobold'],
        '6,4' : ['orc', 'kobold', 'kobold'],
        '6,5' : ['orc', 'kobold', 'kobold'],
        '6,6' : ['orc', 'kobold', 'kobold'],
        '6,7' : ['orc', 'kobold', 'kobold'],
        '6,8' : ['orc', 'kobold', 'kobold'],
        '6,9' : ['orc', 'kobold', 'kobold'],
        '7,0' : ['orc', 'kobold', 'kobold'],
        '7,1' : ['orc', 'kobold', 'kobold'],
        '7,2' : ['orc', 'kobold', 'kobold'],
        '7,3' : ['orc', 'kobold', 'kobold'],
        '7,4' : ['orc', 'kobold', 'kobold'],
        '7,5' : ['orc', 'kobold', 'kobold'],
        '7,6' : ['orc', 'kobold', 'kobold'],
        '7,7' : ['orc', 'kobold', 'kobold'],
        '7,8' : ['orc', 'kobold', 'kobold'],
        '7,9' : ['orc', 'kobold', 'kobold'],
        '8,0' : ['orc', 'kobold', 'kobold'],
        '8,1' : ['orc', 'kobold', 'kobold'],
        '8,2' : ['orc', 'kobold', 'kobold'],
        '8,3' : ['orc', 'kobold', 'kobold'],
        '8,4' : ['orc', 'kobold', 'kobold'],
        '8,5' : ['orc', 'kobold', 'kobold'],
        '8,6' : ['orc', 'kobold', 'kobold'],
        '8,7' : ['orc', 'kobold', 'kobold'],
        '8,8' : ['orc', 'kobold', 'kobold'],
        '8,9' : ['orc', 'kobold', 'kobold'],
        '9,0' : ['orc', 'kobold', 'kobold'],
        '9,1' : ['orc', 'kobold', 'kobold'],
        '9,2' : ['orc', 'kobold', 'kobold'],
        '9,3' : ['orc', 'kobold', 'kobold'],
        '9,4' : ['orc', 'kobold', 'kobold'],
        '9,5' : ['orc', 'kobold', 'kobold'],
        '9,6' : ['orc', 'kobold', 'kobold'],
        '9,7' : ['orc', 'kobold', 'kobold'],
        '9,8' : ['orc', 'kobold', 'kobold'],
        '9,9' : ['orc', 'kobold', 'kobold'],
    }

    var map = {

        init: function() {
            map.addTr();
            map.attachHandlers();
        },

        attachHandlers: function() {
            $('#console-input').on('keyup', function(event) {
                if (event.keyCode == 13) {
                    map.handleInput(event);
                    $(event.target).val('');
                }
            });
        },

        /**
         * Js solution of making a bunch of tr's
         * @return undefined
         */
        addTr: function() {
            var tBody = $('body.map').find('tbody');

            for (i = 0; i < 10; i++) {
                tBody.append('<tr></tr>');
            }

            map.addTd();
        },

        /**
         * Js solution of making a bunch of td's for each tr`
         * @return undefined
         */
        addTd: function() {
            var selector = $('body.map tbody tr');

            $(selector).each(function(index, tr) {

                for (i = 0; i < 10; i++) {
                    $(tr).append('<td></td>');
                }
            });

            map.setActiveTile();
        },

        /**
         * Set active tile on the map. If no location is given the default is
         * 5,5.
         * @var location array
         * @return undefined
         */
        setActiveTile: function(location) {
            var table = $('body.map').find('tbody');
            var location = location || [5,5];

            table.find('tr:nth-child(' + location[0] + ')')
                 .find('td:nth-child(' + location[1] + ')')
                 .addClass('active');
        },

        /**
         * Handles the input of the map
         * @var event obj
         * @return undefined
         */
        handleInput: function(event) {
            var direction = $('#console-input').val();

            if (! (direction == 'n' || 's' || 'e' || 'w')) {
                console.log('geen windrichting');
                return;
            } else {
                map.handleMove(direction);
                map.getTileContent(map.getActiveTileLocation());
            }
        },

        /**
         * Handles the movement on the map, i.e. change the active tile location.
         * Only reacts to cardinal directions.
         * @var direction string
         * @return undefined
         */
        handleMove: function(direction) {
            var activeTile = $('body.map').find('td.active');

            switch (direction) {
                case 'n':
                    var location = map.getActiveTileLocation();
                    location[0] = location[0] - 1;
                    map.setActiveTile(location);
                    $(activeTile).removeClass('active');
                    break;
                case 's':
                    var location = map.getActiveTileLocation();
                    location[0] = location[0] + 1;
                    map.setActiveTile(location);
                    $(activeTile).removeClass('active');
                    break;
                case 'w':
                    var location = map.getActiveTileLocation();
                    location[1] = location[1] - 1;
                    map.setActiveTile(location);
                    $(activeTile).removeClass('active');
                    break;
                case 'e':
                    var location = map.getActiveTileLocation();
                    location[1] = location[1] + 1;
                    map.setActiveTile(location);
                    $(activeTile).removeClass('active');
                    break;
            }
        },

        /**
         * Gets the coordinates of the active map tile.
         * @return location array
         */
        getActiveTileLocation: function() {
            var location = [];

            $('body.map tbody tr').each(function(rowIndex, row) {

                $(row).find('td').each(function(cellIndex, cell) {
                    if ($(cell).hasClass('active')) {
                        location = [rowIndex + 1, cellIndex + 1];
                    }
                });
            });

            return location;
        },

        getTileContent: function(location) {
            console.log('You encounter: ' + tiles[location.toString()][0] + ', '
                                          + tiles[location.toString()][1] + ', '
                                          + tiles[location.toString()][1]);
        }
    };

    map.init();
</script>
