<!doctype html>

<html>
<head>
    <meta charset="utf-8">
    <!-- <link rel="stylesheet/less" href="style.less"> -->
    <!-- <script src="../less/dist/less.js" type="text/javascript"></script> -->
    <!-- <script src="../jquery/jquery-2.2.2.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<style>
    body {
        position: relative;
    }

    .option {
        display: block;
        cursor: pointer;
    }

    .hp {
        position: absolute;
        top: 100px;
        right: 100px;
    }

    .monster {
        position: absolute;
        top: 200px;
        right: 100px;
    }

    .result {
        color: red;
    }
</style>

<p>
    You encounter a monster. What do you do?
</p>

<div class="hp">
HP:<span>100</span>
</div>

<div class="monster">
HP: <span>50</span>
</div>

<div>
    <span data-option="attack" class="option">Attack</span>
    <span data-option="flee" class="option">Flee</span>
    <span data-option="something" class="option">Something else</span>
</div>

<p class="response">

</p>

<script>
    game = {
        ownHP: $('.hp span').html(),
        monsterHP: $('.monster span').html(),

        init: function() {
            game.attachHandlers();
        },

        attachHandlers: function() {
            $('[data-option="attack"]').click(game.handleAttack);
            $('[data-option="flee"]').click(game.handleFlee);
        },

        handleAttack: function(event) {
            // var ownHP = $('.hp span').html();
            // var monsterHP = $('.monster span').html();

            console.log(game.ownHP, game.monsterHP);
            $('body').append('You attack the monster.');
            game.attackLoop();
        },

        attackLoop: function() {
            game.attack();

            setTimeout(function() {
                if (game.monsterHP > 0){
                    game.attackLoop();
                }
            }, 1000);
        },

        attack: function() {
            var ownDamage = game.calculateDamage();

            $('body').append('<p>You hit the monster for ' + ownDamage + ' damage.</p>');

            // calculate and echo monster HP
            game.calculateMonsterHP(ownDamage);
            $('.monster span').html(game.monsterHP);

            // Echo monster death message
            if (game.monsterHP <= 0) {
                $('body').append('<p class="result">The monster is dead. You killed it. It turned out to be a really friendly monster. Are you happy?</p>')
            }
        },

        calculateDamage: function() {
            var ownDamage = Math.floor(Math.random() * 6) + 4;

            return ownDamage;
        },

        calculateMonsterHP: function(ownDamage) {
            game.monsterHP -= ownDamage;

            if (game.monsterHP < 0)
                game.monsterHP = 0;
        },

        handleFlee: function() {
            $('body').append('<p>Oh c\'mon. REALLY?');
        }
    }

    game.init();
</script>


</body>
</html>
