<!doctype html>

<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet/less" href="source/less/style.less">
    <script async type="text/javascript" src="source/js/less.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
<p>
    You encounter a monster. What do you do?
</p>

<div class="hero">
HP: <span>100</span>
</div>

<div class="monster">
HP: <span>50</span>
</div>

<div class="console-window">

</div>

<input id="console-input" type="text" />

<script>
    game = {
        heroHP: $('.hero span').html(),
        monsterHP: $('.monster span').html(),
        heroCritChance: 15,
        monsterCritChance: 15,

        init: function() {
            game.attachHandlers();
        },

        attachHandlers: function() {
            $('#console-input').on('keyup', function(event) {
                if (event.keyCode == 13) {
                    game.handleInput();
                    $(event.target).val('');
                }
            });
        },

        handleInput: function() {
            var input = $('#console-input').val();

            switch (input) {
                case 'attack':
                    game.handleAttack();
                    break;
                case 'flee':
                    game.handleFlee();
                    break;
                default:
                    game.printToConsole('Excuse me?');
                    break;
            }
        },

        printToConsole: function(message) {
            $('.console-window').append('<p>' + message + '</p>');

            $('.console-window').scrollTop(
                $('.console-window p:last-child').position().top
            );
        },

        handleAttack: function() {
            game.printToConsole('You attack the monster.');
            game.attackLoop();
        },

        attackLoop: function() {
            game.attack();

            setTimeout(function() {
                if (game.monsterHP > 0 && game.heroHP > 0){
                    game.attackLoop();
                }
            }, 1000);
        },

        hit: function(person) {
            var dodge = 0;

            if (person == 'hero') {
                dodge = players.hero.dodge;
            } else if (person == 'monster') {
                dodge = monsters.kobold.dodge;
            }

            var number = game.generateRandomNumber();
            console.log(number);
            return number <= dodge ? false : true;;
        },

        attack: function() {
            if (game.hit('monster')) {
                var heroDamage = game.calculateHeroDamage();
                var heroHitMessage = 'You <em>' + (heroDamage['crit'] > 1 ? 'CRIT' : 'hit') + '</em> the monster for ' + heroDamage['damage'] + ' damage.';
                game.calculateMonsterHP(heroDamage['damage']);
                $('.monster span').html(game.monsterHP);
                game.printToConsole(heroHitMessage);
            } else {
                var heroHitMessage = 'Your attack misses!'
                game.printToConsole(heroHitMessage);
            }

            if (game.hit('hero')) {
                var monsterDamage = game.calculateMonsterDamage();
                var monsterHitMessage = 'The monster <em>' + (monsterDamage['crit'] > 1 ? 'CRITS' : 'hits') + '</em> you for ' + monsterDamage['damage'] + ' damage.';
                game.calculateHeroHP(monsterDamage['damage']);
                $('.hero span').html(game.heroHP);
                game.printToConsole(monsterHitMessage);
            } else {
                var monsterHitMessage = 'The monster attack misses!'
                game.printToConsole(monsterHitMessage);
            }

            // Echo monster death message
            if (game.monsterHP <= 0) {
                game.printToConsole('<p class="result">The monster is dead. You killed it. It turned out to be a really friendly monster. Are you happy?')
            }

            if (game.heroHP <= 0) {
                gamme.printToConsole('<p class="result">You have died. No exp for you. Are you sure this is the right game for you?');
            }
        },

        calculateHeroDamage: function() {
            var multiplier = game.calculateCritMultiplier('hero');
            return {
                damage: (Math.floor(Math.random() * 6) + 4) * multiplier,
                crit: multiplier,
            };
        },

        calculateMonsterDamage: function() {
            var multiplier = game.calculateCritMultiplier('monster');
            return {
                damage: (Math.floor(Math.random() * 4) + 1) * multiplier,
                crit: multiplier,
            }
        },

        calculateCritMultiplier: function(person) {
            var random = game.generateRandomNumber();

            if (person == 'hero') {
                critChance = game.heroCritChance;
            } else if (person == 'monster') {
                critChance = game.monsterCritChance;
            }

            return random <= critChance ? 2 : 1;
        },

        calculateMonsterHP: function(heroDamage) {
            game.monsterHP -= heroDamage;

            if (game.monsterHP < 0)
                game.monsterHP = 0;
        },

        calculateHeroHP: function(monsterDamage) {
            game.heroHP -= monsterDamage;

            if (game.heroHP < 0)
                game.heroHP = 0;
        },

        generateRandomNumber: function(range) {
            var range = range || 100;
            return Math.floor(Math.random() * range) + 1;
        },

        handleFlee: function() {
            game.printToConsole('Oh c\'mon. REALLY?');
        },
    }
    game.init();

    players = {

        hero: {
            'dodge': 5
        },
    }

    monsters = {

        kobold: {
            'dodge': 5
        },
    }
</script>
</body>
</html>
